language: node_js
node_js:
  - '0.8'
  - '0.10'
before_script:
  - 'npm install -g bower grunt-cli'
  - 'bower install'
script:
  - karma start --reporters dots --browsers Firefox,PhantomJS --single-run